### ISSUE TITLE
JSX Fragments Not Supported

### ISSUE THREAD

**Issue by lukescott** [atom/language-typescript#19]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

JSX Fragments are not supported.

### Steps to Reproduce

1. Open a new file and set file type to TypeScriptReact
2. Input code `const fragment = <></>`

**Expected behavior:**

Syntax should be supported and shouldn't show as invalid characters.

What Babel ES6 JavaScript does:

![screen shot 2018-03-21 at 1 52 41 pm](https://user-images.githubusercontent.com/486224/37736815-2687b148-2d0f-11e8-954a-7087f9f98858.png)

**Actual behavior:**

Syntax is not supported and shows as invalid.

What TypeScriptReact does:

![screen shot 2018-03-21 at 1 52 15 pm](https://user-images.githubusercontent.com/486224/37736802-19d2a746-2d0f-11e8-807b-96f58c805f75.png)

**Reproduces how often:** Always.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.10
git 2.13.2
os OS X 10.12.2

### Additional Information

JSX Fragments are currently supported in TypeScript 2.6. Closed issue https://github.com/Microsoft/TypeScript/issues/19094.

**Comment by Igor10k** [comment]
looks like the JSX fragment issue was fixed in the original grammar long time ago (https://github.com/Microsoft/TypeScript-TmLanguage/pull/535) but was never copied to this repo

**Comment by gavinlight** [comment]
Any updates on this? It's been a year and it's still not working

**Comment by bigidea-kz** [comment]
OMG 23.05.2019 fragment not supported in atom ))))))))))))))))))))))))))))
Crazy?

**Comment by GaddMaster** [comment]
any update ?
